AWSTemplateFormatVersion: 2010-09-09
Description: S3 / Route53 / CloudFront / CloudFormation configuration

Parameters:
  DomainName:
    Description: SecNet
    Type: String

Resources:

#bucket for website logs
  S3LogBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete 
    Properties: 
      AccessControl: LogDeliveryWrite
      BucketName: !Sub '${AWS::StackName}-logs'


#root bucket for website
  S3BucketRoot:
    Type: AWS::S3::Bucket 
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub '${AWS::StackName}-root'
      LoggingConfiguration:
        DestinationBucketName: !Ref S3LogBucket
        LogFilePrefix: 'cdn/'
      WebsiteConfiguration:
        ErrorDocument: '404.hmtl'
        IndexDocument: 'index.html'


#bucket policy
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketRoot
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Action: 's3:GetObject'
            Principal: "*"
            Resource: !Sub '${S3BucketRoot.ARN}/*'

#certificate
  CertificateManagerCert:
    Type: AWS::CertificateManager::CertificateManager
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS


#cloudfrontdistribution      
  CloudFrontDist:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods: 
            - GET 
            - HEAD
          Compress: true 
          DefaultTTL: 86400
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true 
          MaxTTL: 31535000
          SmoothStreaming: false
          TargetOriginID: !Sub 'S3-${AWS::StackName}-root'
          ViewerProtocolPolicy: 'redirect-to-https'
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/404.htmnl'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Loggong: 
          Bucket: !GetAtt S3LogBucket.DomainName
          IncludeCookies: false
          Prefix: 'cdn/'
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 5
              OriginProtocolPolicy: 'only-https'
              OriginReadTimeout: 30
              OriginSSLProtocols:
                - TLSv1
                - TLSv1.1
                - TLSv1.2
            DomainName: !GetAtt S3BucketRoot.DomainName
            Id: !Sub 'S3-${AWS::StackName}-root'
        PriceClass: PriceClass_All
        ViewerVertificate:
          AcmCertificateARN: !Ref CertificateManagerCert
          MinimumProtocolVersion: TLSv1.1_2016
          SskSupportMethod: sni-only

  #routing policy to cf distribution
  Route53RecordSetGroup: 
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZone: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Ref DomainName
          Type: A 
          AliadTarget:
            DNSName: !GetAtt CloudFrontDist.DomainName 
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: !Sub 'www.${DomainName}' 
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudFrontDist.DomainName
            EvaluateTargetHealth: false
            HostedZoneId: Z2FDTNDATAQYW2
    
          
